replicaCount: 2

backend:
  image: "228449306376.dkr.ecr.us-east-1.amazonaws.com/church-backend"
  tag: "latest"
  port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  image: "228449306376.dkr.ecr.us-east-1.amazonaws.com/church-frontend"
  tag: "latest"
  port: 3000
  type: LoadBalancer  # Exposes externally

rds_endpoint: "church-eks-cluster-postgres.c0zsssao0dnu.us-east-1.rds.amazonaws.com:5432"  # e.g., church-eks-cluster-postgres.abcd123.us-east-1.rds.amazonaws.com:5432

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 70