apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: church-app-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: church-app-backend
  template:
    metadata:
      labels:
        app: church-app-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: DB_NAME
          value: "church_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_HOST
          value: "{{ .Values.rds_endpoint }}"
        - name: DB_PORT
          value: "5432"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret_key
        - name: DJANGO_DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "{{ .Values.backend.allowedHosts }}"
        resources:
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: church-app-backend
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  type: ClusterIP